import React from 'react';
import { Zap, FileText, Lightbulb, Mic2, TrendingUp, Target } from 'lucide-react';

const features = [
  {
    icon: Zap,
    title: 'AI Roadmaps',
    description: 'Get personalized career roadmaps generated by AI based on your interests and college timeline.'
  },
  {
    icon: FileText,
    title: 'Resume Builder',
    description: 'Craft a compelling resume with AI suggestions and industry-best practices tailored to tech roles.'
  },
  {
    icon: Lightbulb,
    title: 'Project Generator',
    description: 'Generate real-world project ideas that showcase your skills and impress recruiters.'
  },
  {
    icon: Mic2,
    title: 'Mock Interviews',
    description: 'Practice with AI-powered mock interviews and get detailed feedback on your performance.'
  },
  {
    icon: TrendingUp,
    title: 'Progress Tracking',
    description: 'Monitor your skill development and career progress with detailed analytics and insights.'
  },
  {
    icon: Target,
    title: 'Placement Prep',
    description: 'Get comprehensive preparation for placements with company-specific interview guidance.'
  }
];

export default function FeaturesSection() {
  return (
    <section className="relative py-20 px-4 sm:px-6 lg:px-8 bg-surface-950">
      <div className="max-w-7xl mx-auto">
        {/* Section Header */}
        <div className="text-center mb-16">
          <div className="inline-block mb-4 px-4 py-2 rounded-full bg-white/5 backdrop-blur border border-white/10">
            <p className="text-sm font-medium text-primary-400">Features</p>
          </div>
          <h2 className="text-4xl sm:text-5xl font-bold mb-4">
            <span className="gradient-text">Everything You Need</span>
            {' '}
            <span className="text-white">to Succeed</span>
          </h2>
          <p className="text-lg text-gray-400 max-w-2xl mx-auto">
            Comprehensive tools designed to guide you from your first year through successful placement.
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <div
                key={index}
                className="group relative p-8 rounded-2xl bg-white/5 backdrop-blur border border-white/10 hover:border-primary-500/50 transition-all duration-300 hover:bg-white/10"
              >
                {/* Gradient background on hover */}
                <div className="absolute inset-0 bg-gradient-to-br from-primary-500/10 to-transparent rounded-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300 -z-10" />

                {/* Icon */}
                <div className="inline-flex items-center justify-center w-12 h-12 rounded-lg bg-primary-500/20 text-primary-400 mb-4 group-hover:bg-primary-500/30 transition-colors">
                  <Icon size={24} />
                </div>

                {/* Content */}
                <h3 className="text-xl font-semibold text-white mb-3">
                  {feature.title}
                </h3>
                <p className="text-gray-400 leading-relaxed">
                  {feature.description}
                </p>

                {/* Accent line */}
                <div className="absolute bottom-0 left-0 h-1 bg-gradient-to-r from-primary-500 to-transparent rounded-full w-0 group-hover:w-full transition-all duration-300" />
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
